project:
  type: website

website:
  title: "blog"
  site-url: https://romainligneul.github.io/fr/blog/
  description: "Blog R. Ligneul"
  navbar:
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme: cerulean
    css: ../../../custom.scss



