project:
  title: "RL  "
  output-dir: ./docs/en
  render:
  - "./fr/"

website:
  navbar:
    left:
      - href: fr/index.qmd
        text: Accueil
      - href: fr/blog/
        text: Blog
      - href: fr/recherche.qmd
        text: Recherche
      - href: fr/robustcircuit.qmd
        text: Startup
      - text: Science citoyenne
        menu:
          - text: "Quiz électoraux (2022)"
            file: fr/science-citoyenne/quiz_elections.qmd
          - text: "Biais réseaux sociaux (2017)"
            file: fr/science-citoyenne/biais_reseaux.qmd
    right:
      - href: "./"
        text: EN
      - href: ./fr
        text: FR
  page-footer: 
    left: "Copyright 2024, Romain Ligneul" 
    right: 
      - icon: github
        href: https://github.com/romainligneul
      - icon: twitter 
        href: https://twitter.com/nerfsocial
      - icon: linkedin 
        href: https://www.linkedin.com/in/romain-ligneul-b63b46192/
      - icon: lightbulb 
        href: https://www.adaptivecontrol.org

format:
  html:
    theme: 
      - cerulean
      - ../../custom.scss
    toc: true