project:
  title: "RL | "
  output-dir: ./docs/
  render:
  - "./en/"

website:
  navbar:
    left:
      - href: ./en/index.qmd
        text: Home
      - href: en/codes.qmd
        text: Code
    right:
      - href: ./en
        text: EN
      - href: ./en/fr
        text: FR
        
format:
  html:
    theme: 
      - cerulean
      - ../custom.scss
    toc: true