project:
  title: "Romain Ligneul | Personal page"
  output-dir: ./docs/
  render:
  - "./en/"

website:
  body-header: |
    <link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('/fr/','/en/');" class="btn"><i class="fa fa-language"></i> FR </button>
  navbar:
    left:
      - href: en/index.qmd
        text: Home
      - href: en/codes.qmd
        text: Code
    right:
      - href: en/index.qmd
        text: EN
      - href: en/fr/index.qmd
      - text: FR
        
format:
  html:
    theme: 
      - cerulean
      - ../custom.scss
    toc: true