project:
  title: "RL | "
  output-dir: ./docs/en
  render:
  - "./fr/"

website:
  navbar:
    left:
      - href: fr/index.qmd
        text: Accueil
      - href: fr/blog/
        text: Blog
      - href: fr/work.qmd
        text: Travail
    right:
      - href: en/index.qmd
        text: EN
      - href: ../fr/index.qmd
      - text: FR

format:
  html:
    theme: 
      - cerulean
      - ../custom.scss
    toc: true