project:
  title: "RL | "
  output-dir: ./docs/
  render:
  - "./en/"

website:
  navbar:
    left:
      - href: en/index.qmd
        text: Home
      - href: en/codes.qmd
        text: Code
    right:
      - href: index.qmd
        text: EN
      - href: fr/index.qmd
      - text: FR
        
format:
  html:
    theme: 
      - cerulean
      - ../custom.scss
    toc: true