project:
  type: website
  output-dir: ./docs

website:
  site-url: https://romainligneul.github.io
  description: "Romain Ligneul"
  twitter-card: true
  open-graph:
    site-name: Romain Ligneul
  favicon: favicon.ico
execute:
  freeze: auto

profile:
  default: french
  group: [english, french]