project:
  title: "Romain Ligneul | Page personnelle"
  output-dir: ./docs/en
  render:
  - "./fr/"

website:
  body-header: |
    <link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('/en/','/fr/');" class="btn"><i class="fa fa-language"></i> EN </button>
  navbar:
    left:
      - href: fr/index.qmd
        text: Accueil
      - href: fr/work.qmd
        text: Travail
    right:
      - href: en/index.qmd
        text: EN
      - href: en/fr/index.qmd
      - text: FR

format:
  html:
    theme: 
      - cerulean
      - ../custom.scss
    toc: true