project:
  type: website
  output-dir: ./docs

website:
  site-url: https://romainligneul.github.io
  description: "Romain Ligneul"
execute:
  freeze: auto

profile:
  default: french
  group: [english, french]