project:
  title: "RL  "
  output-dir: ./docs/
  render:
  - "./en/"

website:
  navbar:
      tools:
        - icon: github
          href: https://github.com/romainligneul
        - icon: twitter 
          menu:
          - text: Academic (EN)
            href:  https://twitter.com/causalself
          - text: Eclectic (FR)
            href:  https://twitter.com/nerfsocial
        - icon: linkedin 
          href: https://www.linkedin.com/in/romain-ligneul-b63b46192/
        - icon: lightbulb 
          href: https://www.adaptivecontrol.org
    left:
      - href: ./en/index.qmd
        text: Home
      - href: en/codes.qmd
        text: Code
    right:
      - href: ./en
        text: EN
      - href: ./en/fr
        text: FR
  page-footer: 
    left: "Copyright 2024, Romain Ligneul" 

        
format:
  html:
    theme: 
      - cerulean
      - ../custom.scss
    toc: true